export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

export const SUBMIT_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';

export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';

export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
